name: Deploy

on:
  push:
    branches: [ master, develop ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Build executable
      run: |
        pyinstaller --onefile --name=stashable src/cli.py
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: stashable
        path: src/dist/stashable